name = "sikai-content"
main = "src/index.ts"
compatibility_date = "2025-01-15"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "sikai-content"
database_id = "86db99d2-2eaa-4c7a-9f4d-abfa0c143a99"



[vars]
ALLOWED_ORIGIN = "*"